// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwMxGHSB8PS93W_H56TX7YXFeplWpATf4',
    appId: '1:526290186644:web:5af093bb0df197bb965f81',
    messagingSenderId: '526290186644',
    projectId: 'clickfarma-gbarros',
    authDomain: 'clickfarma-gbarros.firebaseapp.com',
    storageBucket: 'clickfarma-gbarros.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd96wV2s2ZCA0kUyZYHU32QXQRhrGLAgM',
    appId: '1:526290186644:android:5a725476d8e78fa8965f81',
    messagingSenderId: '526290186644',
    projectId: 'clickfarma-gbarros',
    storageBucket: 'clickfarma-gbarros.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcypKtZzbtw8pGpXWSYi3nKuko5oiCA9w',
    appId: '1:526290186644:ios:49726c66d2353937965f81',
    messagingSenderId: '526290186644',
    projectId: 'clickfarma-gbarros',
    storageBucket: 'clickfarma-gbarros.firebasestorage.app',
    iosClientId: '526290186644-jif7imbpu8mcfd18up4gv91hful9rmbc.apps.googleusercontent.com',
    iosBundleId: 'com.example.appclickfarma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwMxGHSB8PS93W_H56TX7YXFeplWpATf4',
    appId: '1:526290186644:web:1fcfe9ceff0ae148965f81',
    messagingSenderId: '526290186644',
    projectId: 'clickfarma-gbarros',
    authDomain: 'clickfarma-gbarros.firebaseapp.com',
    storageBucket: 'clickfarma-gbarros.firebasestorage.app',
  );
}
